### ISSUE TITLE
'str' object is not callable

### ISSUE THREAD

**Issue by Apside-bdx-BBO** [addok/addok#143]
De petites erreurs de lancement de fonctions (en String) provenant de 'config.default.py' apparaissent.
Le problème est corrigé localement en y ajoutant à la ligne 109 de 'addok.index': 
``` Python
    f = eval(indexer)
    f(pipe, key, doc, tokens, **kwargs)
```
Et à la ligne (122-123)  de addok.index' de la fonction 'deindex_document(id_, **kwargs) :
``` Python
    f = eval(indexer)
    f(DB, key, doc, tokens, **kwargs)

```

Cependant, le fonctionnement semble impacté en profondeur.

**Comment by yohanboniface** [comment]
Tu peux paster la stacktrace complète? Quelle version d'addok tu utilises, 0.5.0 ou le master (le master est très instable ces jours-ci, il vaut mieux ne pas l'utiliser ;) )?

**Comment by Apside-bdx-BBO** [comment]
Hé hé, mauvaise pioche pour moi, c'est le Master que j'utilise... :)

Avant les corrections (dsl, pas d'accès pastebin sur place :( ...)

``` Bash
Addok loaded plugins: addok.batch, addok.shell, addok.fuzzy, addok.update, addok.http
Import from file C:\xxxxxx\xxxxxx\verysimple3.sjson
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\python34\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\python34\Lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 54, in process
    index_document(doc, update_ngrams=False)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\helpers\index.py", line 108, in index_document
    indexer(pipe, key, doc, tokens, **kwargs)
TypeError: 'str' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\xxxxxx\xxxxxx\Dev/workspace/addok/addok/bin/__init__.py", line 33, in <module>
    main()
  File "C:\xxxxxx\xxxxxx\Dev/workspace/addok/addok/bin/__init__.py", line 25, in main
    args.func(args)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 14, in run
    process_file(path)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 34, in process_file
    batch(map(preprocess_batch, f))
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 72, in batch
    pool.map(process, chunk)
  File "c:\python34\Lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\python34\Lib\multiprocessing\pool.py", line 599, in get
    raise self._value
TypeError: 'str' object is not callable
``` 

Apres les corrections:

``` Bash
multiprocessing.pool.RemoteTraceback: 
Traceback (most recent call last):
  File "c:\python34\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\python34\Lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 54, in process
    index_document(doc, update_ngrams=False)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\helpers\index.py", line 110, in index_document
    f(pipe, key, doc, tokens, **kwargs)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\helpers\index.py", line 192, in fields_indexer
    extract_tokens(tokens, value, boost=boost)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\helpers\index.py", line 73, in extract_tokens
    els = list(preprocess(string))
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\helpers\index.py", line 19, in preprocess
    _CACHE[s] = list(iter_pipe(s, config.PROCESSORS))
  File "C:\Users\xxxxxx\Dev\workspace\addok\addok\helpers\__init__.py", line 10, in iter_pipe
    pipe = it(pipe)
TypeError: 'str' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\pydevd.py", line 2407, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\pydevd.py", line 1798, in run
    launch(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "C:\xxxxxx\xxxxxx\/Dev/workspace/addok/addok/bin/__init__.py", line 33, in <module>
    main()
  File "C:\xxxxxx\xxxxxx\Dev/workspace/addok/addok/bin/__init__.py", line 25, in main
    args.func(args)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 14, in run
    process_file(path)
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 34, in process_file
    batch(map(preprocess_batch, f))
  File "C:\xxxxxx\xxxxxx\Dev\workspace\addok\addok\batch.py", line 72, in batch
    pool.map(process, chunk)
  File "c:\python34\Lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\python34\Lib\multiprocessing\pool.py", line 599, in get
    raise self._value
TypeError: 'str' object is not callable

```

**Comment by yohanboniface** [comment]
Reste sur 0.5.0 pour l'instant, c'est plus sûr. Le master est la future 1.0.0, et je suis en plein refactoring.

**Comment by Apside-bdx-BBO** [comment]
ok
