### ISSUE TITLE
redis WRONGTYPE

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#170]
Time by time addok raise an error. The error is not reproducible.
Version 0.5.
See at this two different stacktrace.

```
May 24 21:33:31 geocode addok-wrapper[29535]: RestClient.get "http://localhost:7878/search2steps?limit=1&autocomplete=0&q0=59000+LILLE&q=rue+de+gand+59000", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate"
May 24 21:33:31 geocode addok[28440]: [2016-05-24 21:33:31 +0200] [28453] [ERROR] Error handling request /search2steps?limit=1&autocomplete=0&q0=59000+LILLE&q=rue+de+gand+59000

May 24 21:33:31 geocode addok[28440]: Traceback (most recent call last):
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 130, in handle
May 24 21:33:31 geocode addok[28440]: self.handle_request(listener, req, client, addr)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
May 24 21:33:31 geocode addok[28440]: respiter = self.wsgi(environ, resp.start_response)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 63, in app
May 24 21:33:31 geocode addok[28440]: response = View.serve(endpoint, request, **kwargs)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 105, in serve
May 24 21:33:31 geocode addok[28440]: response = view.get(**kwargs)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/addok/search2steps.py", line 94, in get
May 24 21:33:31 geocode addok[28440]: results = search2steps(self.config, q0, q, autocomplete=autocomplete, limit=limit, lat=lat, lon=lon, **filters)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/addok/search2steps.py", line 44, in search2steps
May 24 21:33:31 geocode addok[28440]: results_step_2 = search(query2 + ' ' + query_step_1, limit=limit, autocomplete=autocomplete, **filters_step_2)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 778, in search
May 24 21:33:31 geocode addok[28440]: return helper(query, lat=lat, lon=lon, **filters)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 401, in __call__
May 24 21:33:31 geocode addok[28440]: if step():
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 462, in step_bucket_with_meaningful
May 24 21:33:31 geocode addok[28440]: self.new_bucket(self.keys, self.SMALL_BUCKET_LIMIT)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 662, in new_bucket
May 24 21:33:31 geocode addok[28440]: self.bucket = self.intersect(keys, limit)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 648, in intersect
May 24 21:33:31 geocode addok[28440]: ids = DB.zrevrange(self.query, 0, limit - 1)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 1766, in zrevrange
May 24 21:33:31 geocode addok[28440]: return self.execute_command(*pieces, **options)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 573, in execute_command
May 24 21:33:31 geocode addok[28440]: return self.parse_response(connection, command_name, **options)
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 585, in parse_response
May 24 21:33:31 geocode addok[28440]: response = connection.read_response()
May 24 21:33:31 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/connection.py", line 582, in read_response
May 24 21:33:31 geocode addok[28440]: raise response
May 24 21:33:31 geocode addok[28440]: redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

```
May 25 12:13:04 geocode addok-wrapper[29535]: RestClient.get "http://localhost:7878/search2steps?limit=1&autocomplete=0&q0=59000+LA+MADELEINE&q=Rue+PAUL+DOUMER+59000", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate"
May 25 12:13:04 geocode addok[28440]: [2016-05-25 12:13:04 +0200] [28458] [ERROR] Error handling request /search2steps?limit=1&autocomplete=0&q0=59000+LA+MADELEINE&q=90+Rue+PAUL+DOUMER+59000
May 25 12:13:04 geocode addok[28440]: Traceback (most recent call last):
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 130, in handle
May 25 12:13:04 geocode addok[28440]: self.handle_request(listener, req, client, addr)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
May 25 12:13:04 geocode addok[28440]: respiter = self.wsgi(environ, resp.start_response)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 63, in app
May 25 12:13:04 geocode addok[28440]: response = View.serve(endpoint, request, **kwargs)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 105, in serve
May 25 12:13:04 geocode addok[28440]: response = view.get(**kwargs)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/addok/search2steps.py", line 94, in get
May 25 12:13:04 geocode addok[28440]: results = search2steps(self.config, q0, q, autocomplete=autocomplete, limit=limit, lat=lat, lon=lon, **filters)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/addok/search2steps.py", line 44, in search2steps
May 25 12:13:04 geocode addok[28440]: results_step_2 = search(query2 + ' ' + query_step_1, limit=limit, autocomplete=autocomplete, **filters_step_2)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 778, in search
May 25 12:13:04 geocode addok[28440]: return helper(query, lat=lat, lon=lon, **filters)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 401, in __call__
May 25 12:13:04 geocode addok[28440]: if step():
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 511, in step_extend_results_reducing_tokens
May 25 12:13:04 geocode addok[28440]: self.reduce_tokens()
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 633, in reduce_tokens
May 25 12:13:04 geocode addok[28440]: self.add_to_bucket(keys)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 656, in add_to_bucket
May 25 12:13:04 geocode addok[28440]: self.bucket.update(self.intersect(keys, limit))
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 648, in intersect
May 25 12:13:04 geocode addok[28440]: ids = DB.zrevrange(self.query, 0, limit - 1)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 1766, in zrevrange
May 25 12:13:04 geocode addok[28440]: return self.execute_command(*pieces, **options)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 573, in execute_command
May 25 12:13:04 geocode addok[28440]: return self.parse_response(connection, command_name, **options)
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 585, in parse_response
May 25 12:13:04 geocode addok[28440]: response = connection.read_response()
May 25 12:13:04 geocode addok[28440]: File "/srv/addok/.local/share/virtualenvs/addok/lib/python3.4/site-packages/redis/connection.py", line 582, in read_response
May 25 12:13:04 geocode addok[28440]: raise response
May 25 12:13:04 geocode addok[28440]: redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

**Comment by dzaouch** [comment]
Same : https://i.imgur.com/6WL6fbk.png

**Comment by yohanboniface** [comment]
Without a way to reproduce, it's quite hard to debug. Please add any info that can help reproducing.

**Comment by dzaouch** [comment]
Some info : 

My gunicorn server : /home/devel/.virtualenvs/addok/bin/python3.4 /home/devel/.virtualenvs/addok/bin/gunicorn addok.server:app -b 127.0.0.1:8080 --access-logfile /var/log/addok/bano.info.log --error-logfile /var/log/addok/bano.err.log --limit-request-field_size 0 -w 4 -t 0 --threads 8 -D

So i got 4 workers and 8 threads.

Also, when do i got the error : a php script split a file (1M address to geocode) into severals smallers files (10K lines, so aroud 1 000 files), and then calls the addok service 4 at a time with multi_curl php function

**Comment by frodrigo** [comment]
It append time by time on my instance, but is not predictable, event with the same query.

**Comment by frodrigo** [comment]
Can be close ?
