### ISSUE TITLE
Extra RAM consumtion at import

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#223]
Trying to import France with addok-sqlite it still consumes more than 16Go of RAM, and this is just during the "dispatching task" (not yet importing).
Sounds like a leak.

```
Loaded local config from /etc/addok/addok.conf
Addok loaded plugins: addok.shell, addok.http.base, addok.batch, addok.pairs, addok.fuzzy, addok.autocomplete, sqlite, fr, france
Import from file .cache/BAN_odbl.json
Dispatching tasks… | Done: 1280000 | Elapsed: 0:03:42Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 366, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 240, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by yohanboniface** [comment]
Same with a 32Go server, so this is a clear regression. I think it's linked to the way we manage tasks.

**Comment by davidbgk** [comment]
Yes, maybe we should batch the dispatching/execution process too.

**Comment by yohanboniface** [comment]
```
Line #    Mem usage    Increment   Line Contents
================================================
   122     39.8 MiB      0.0 MiB   @profile
   123                             def parallelize(func, iterable, chunk_size, **bar_kwargs):
   124     39.8 MiB      0.0 MiB       bar = Bar(prefix='Dispatching tasks…', **bar_kwargs)
   125                             
   126     39.8 MiB      0.0 MiB       chunk = []
   127     39.8 MiB      0.0 MiB       results = []
   128     42.0 MiB      2.2 MiB       with Pool(processes=os.cpu_count() * 2) as pool:
   129    481.1 MiB    439.0 MiB           for i, item in enumerate(iterable):
   130    481.1 MiB      0.0 MiB               if not item:
   131                                             continue
   132    481.1 MiB      0.0 MiB               chunk.append(item)
   133    481.1 MiB      0.0 MiB               if i and not i % chunk_size:
   134    478.2 MiB     -2.9 MiB                   results.append(pool.apply_async(func, [chunk]))
   135    478.2 MiB      0.0 MiB                   bar(step=chunk_size)
   136    478.2 MiB      0.0 MiB                   chunk = []
   137    481.1 MiB      2.9 MiB           if chunk:
   138    481.1 MiB      0.0 MiB               results.append(pool.apply_async(func, [chunk]))
   139    481.1 MiB      0.0 MiB               bar(step=len(chunk))
   140    481.1 MiB      0.0 MiB           bar.done = 0
   141    481.1 MiB      0.0 MiB           bar.prefix = 'Executing tasks…'
   142    680.1 MiB    199.1 MiB           for r in results:
   143    680.1 MiB      0.0 MiB               bar(step=len(r.get()))
   144    678.5 MiB     -1.6 MiB           bar.finish()
```

**Comment by yohanboniface** [comment]
![pouet](https://cloud.githubusercontent.com/assets/146023/22418681/52c831f0-e6da-11e6-9b33-4ac4be23ad88.png)

**Comment by yohanboniface** [comment]
```diff
diff --git a/addok/helpers/__init__.py b/addok/helpers/__init__.py
index 908e6fe..67fd67c 100644
--- a/addok/helpers/__init__.py
+++ b/addok/helpers/__init__.py
@@ -116,25 +116,33 @@ class Bar(ProgressBar):
     template = '{prefix} {animation} Done: {done} | Elapsed: {elapsed}'
 
 
+from memory_profiler import profile
+
+
+@profile
 def parallelize(func, iterable, chunk_size, **bar_kwargs):
     bar = Bar(prefix='Dispatching tasks…', **bar_kwargs)
 
-    with Pool(processes=os.cpu_count() * 2) as pool:
-        chunk = []
-        results = []
+    chunk = []
+    results = []
+    cpu = os.cpu_count()
+
+    def commit(pool, chunk, results, force=False):
+        results.append(pool.apply_async(func, [chunk]))
+        bar(step=chunk_size)
+        if len(results) == cpu or force:
+            for r in results:
+                bar(step=len(r.get()))
+
+    with Pool(processes=cpu) as pool:
         for i, item in enumerate(iterable):
             if not item:
                 continue
             chunk.append(item)
             if i and not i % chunk_size:
-                results.append(pool.apply_async(func, [chunk]))
-                bar(step=chunk_size)
+                commit(pool, chunk, results)
                 chunk = []
+                results = []
         if chunk:
-            results.append(pool.apply_async(func, [chunk]))
-            bar(step=len(chunk))
-        bar.done = 0
-        bar.prefix = 'Executing tasks…'
-        for r in results:
-            bar(step=len(r.get()))
+            commit(pool, chunk, results, force=True)
         bar.finish()
```

```
Line #    Mem usage    Increment   Line Contents
================================================
   122     38.4 MiB      0.0 MiB   @profile
   123                             def parallelize(func, iterable, chunk_size, **bar_kwargs):
   124     38.4 MiB      0.0 MiB       bar = Bar(prefix='Dispatching tasks…', **bar_kwargs)
   125                             
   126     38.4 MiB      0.0 MiB       chunk = []
   127     38.4 MiB      0.0 MiB       results = []
   128     38.4 MiB      0.0 MiB       cpu = os.cpu_count()
   129                             
   130    523.7 MiB    485.3 MiB       def commit(pool, chunk, results, force=False):
   131    523.7 MiB      0.0 MiB           print("commit")
   132    523.7 MiB      0.0 MiB           results.append(pool.apply_async(func, [chunk]))
   133    523.7 MiB      0.0 MiB           bar(step=chunk_size)
   134    523.7 MiB      0.0 MiB           if len(results) == cpu or force:
   135    523.7 MiB      0.0 MiB               print('executing')
   136    523.7 MiB      0.0 MiB               for r in results:
   137    170.0 MiB   -353.7 MiB                   bar(step=len(r.get()))
   138                             
   139     38.8 MiB   -131.3 MiB       with Pool(processes=cpu) as pool:
   140    523.7 MiB    484.9 MiB           for i, item in enumerate(iterable):
   141    523.7 MiB      0.0 MiB               if not item:
   142                                             continue
   143    523.7 MiB      0.0 MiB               chunk.append(item)
   144    523.7 MiB      0.0 MiB               if i and not i % chunk_size:
   145    520.8 MiB     -2.9 MiB                   commit(pool, chunk, results)
   146    520.8 MiB      0.0 MiB                   chunk = []
   147    520.8 MiB      0.0 MiB                   results = []
   148    523.7 MiB      2.9 MiB           if chunk:
   149    170.0 MiB   -353.7 MiB               commit(pool, chunk, results, force=True)
   150    170.4 MiB      0.4 MiB           bar.finish()
```

**Comment by davidbgk** [comment]
```diff
diff --git a/addok/batch.py b/addok/batch.py
index 34d7689..00b03e4 100644
--- a/addok/batch.py
+++ b/addok/batch.py
@@ -55,8 +55,8 @@ def to_json(row):
         return None
 
 
-def process_documents(docs):
-    return list(iter_pipe(docs, config.DOCUMENT_PROCESSORS))
+def process_documents(doc):
+    return list(iter_pipe([doc], config.DOCUMENT_PROCESSORS))
 
 
 def batch(iterable):
diff --git a/addok/helpers/__init__.py b/addok/helpers/__init__.py
index 908e6fe..938d9a9 100644
--- a/addok/helpers/__init__.py
+++ b/addok/helpers/__init__.py
@@ -3,6 +3,7 @@ from importlib import import_module
 from math import asin, cos, exp, radians, sin, sqrt
 import os
 from multiprocessing import Pool
+import time
 
 from progressist import ProgressBar
 
@@ -113,28 +114,18 @@ def white(s):
 
 class Bar(ProgressBar):
     animation = '{spinner}'
-    template = '{prefix} {animation} Done: {done} | Elapsed: {elapsed}'
+    template = '{prefix} {animation} CPU working: {done} | Elapsed: {elapsed}'
 
 
 def parallelize(func, iterable, chunk_size, **bar_kwargs):
-    bar = Bar(prefix='Dispatching tasks…', **bar_kwargs)
-
-    with Pool(processes=os.cpu_count() * 2) as pool:
-        chunk = []
-        results = []
-        for i, item in enumerate(iterable):
-            if not item:
-                continue
-            chunk.append(item)
-            if i and not i % chunk_size:
-                results.append(pool.apply_async(func, [chunk]))
-                bar(step=chunk_size)
-                chunk = []
-        if chunk:
-            results.append(pool.apply_async(func, [chunk]))
-            bar(step=len(chunk))
-        bar.done = 0
-        bar.prefix = 'Executing tasks…'
-        for r in results:
-            bar(step=len(r.get()))
+    bar = Bar(prefix='Asynchronuous tasks…', **bar_kwargs)
+    processes = os.cpu_count() - 1
+
+    with Pool(processes=processes) as pool:
+        result = pool.map_async(func, iterable, chunk_size)
+        while not result.ready():
+            bar.done = result._number_left
+            bar.render()
+            time.sleep(1)
+        result.get()
         bar.finish()
```

Not happy with the list-ification of the returned `doc` in `process_documentS` but it looks cleaner. It's not faster yet though, but I think it's due to the un-list/re-list-ification.

**Comment by yohanboniface** [comment]
WIP

```
diff --git a/addok/batch.py b/addok/batch.py
index 34d7689..2be95d5 100644
--- a/addok/batch.py
+++ b/addok/batch.py
@@ -55,7 +55,7 @@ def to_json(row):
         return None
 
 
-def process_documents(docs):
+def process_documents(*docs):
     return list(iter_pipe(docs, config.DOCUMENT_PROCESSORS))
 
 
diff --git a/addok/helpers/__init__.py b/addok/helpers/__init__.py
index 908e6fe..61b37a5 100644
--- a/addok/helpers/__init__.py
+++ b/addok/helpers/__init__.py
@@ -2,7 +2,7 @@ from functools import wraps
 from importlib import import_module
 from math import asin, cos, exp, radians, sin, sqrt
 import os
-from multiprocessing import Pool
+from multiprocessing.pool import RUN, IMapUnorderedIterator, Pool
 
 from progressist import ProgressBar
 
@@ -116,25 +116,29 @@ class Bar(ProgressBar):
     template = '{prefix} {animation} Done: {done} | Elapsed: {elapsed}'
 
 
+class CustomPool(Pool):
+
+    def imap_unordered(self, func, iterable, chunksize):
+        assert self._state == RUN
+        task_batches = Pool._get_tasks(func, iterable, chunksize)
+        result = IMapUnorderedIterator(self._cache)
+        self._taskqueue.put(
+            (
+                (
+                    (result._job, i, func, chunk, {})
+                    for i, (_, chunk) in enumerate(task_batches)
+                ),
+                result._set_length
+            )
+        )
+        return result
+
+
 def parallelize(func, iterable, chunk_size, **bar_kwargs):
-    bar = Bar(prefix='Dispatching tasks…', **bar_kwargs)
-
-    with Pool(processes=os.cpu_count() * 2) as pool:
-        chunk = []
-        results = []
-        for i, item in enumerate(iterable):
-            if not item:
-                continue
-            chunk.append(item)
-            if i and not i % chunk_size:
-                results.append(pool.apply_async(func, [chunk]))
-                bar(step=chunk_size)
-                chunk = []
-        if chunk:
-            results.append(pool.apply_async(func, [chunk]))
+    bar = Bar(prefix='Asynchronuous tasks…', **bar_kwargs)
+    processes = os.cpu_count() - 1
+
+    with CustomPool(processes=processes) as pool:
+        for chunk in pool.imap_unordered(func, iterable, chunk_size):
             bar(step=len(chunk))
-        bar.done = 0
-        bar.prefix = 'Executing tasks…'
-        for r in results:
-            bar(step=len(r.get()))
         bar.finish()
  ```

```
Line #    Mem usage    Increment   Line Contents
================================================
   183     38.6 MiB      0.0 MiB   @profile
   184                             def parallelize(func, iterable, chunk_size, **bar_kwargs):
   185     38.6 MiB      0.0 MiB       bar = Bar(prefix='Asynchronuous tasks…', **bar_kwargs)
   186     38.6 MiB      0.0 MiB       processes = os.cpu_count() - 1
   187                             
   188     38.8 MiB      0.2 MiB       with CustomPool(processes=processes) as pool:
   189     99.9 MiB     61.2 MiB           for result in pool.imap_unordered(func, iterable, chunk_size):
   190     99.9 MiB      0.0 MiB               bar(step=len(result))
```
