### ISSUE TITLE
Which version of addok-france and addok-plugin to use

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#231]
Hi,

When running the latest version of `addok-france` and `addok-fr` plugins, it seems I have a version conflict with `addok` version `0.5.0`:

```
Traceback (most recent call last):
  File "/usr/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/addok/bin/__init__.py", line 44, in main
    from addok.debug import Cli
  File "/usr/lib/python3.4/site-packages/addok/debug.py", line 13, in <module>
    from .core import (Search, SearchResult, Token, compute_geohash_key,
  File "/usr/lib/python3.4/site-packages/addok/core.py", line 8, in <module>
    from .index_utils import (PROCESSORS, VALUE_SEPARATOR, document_key,
  File "/usr/lib/python3.4/site-packages/addok/index_utils.py", line 13, in <module>
    PROCESSORS = [import_by_path(path) for path in config.PROCESSORS]
  File "/usr/lib/python3.4/site-packages/addok/index_utils.py", line 13, in <listcomp>
    PROCESSORS = [import_by_path(path) for path in config.PROCESSORS]
  File "/usr/lib/python3.4/site-packages/addok/utils.py", line 22, in import_by_path
    module = import_module(module_path)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.4/site-packages/addok_france/__init__.py", line 1, in <module>
    from addok.helpers import yielder
ImportError: No module named 'addok.helpers'
```

Is it possible to fix a release for both plugins that is compatible with the latest `addok`?

Thanks!

**Comment by yohanboniface** [comment]
Release is coming soon.
For now, stable version is 5.x (thus `pip install addok`), which does not work with plugin (it's "full" France featured).
If you want latest versions, you need to be full up to date with git trunks (see [tutorial](http://addok.readthedocs.io/en/latest/tutorial/)).
