### ISSUE TITLE
pathlib Path.home() causing error

### ISSUE THREAD

**Issue by cquest** [addok/addok#280]
```
Traceback (most recent call last):
  File "/home/addok/.virtualenvs/addok2/bin/addok", line 9, in <module>
    load_entry_point('addok==1.0.0.rc.1', 'console_scripts', 'addok')()
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/bin/__init__.py", line 27, in main
    args.func(args)
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/shell.py", line 477, in invoke
    cmd = Cmd()
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/shell.py", line 38, in __init__
    self._init_history_file()
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/shell.py", line 45, in _init_history_file
    readline.read_history_file(self.history_file)
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/shell.py", line 59, in history_file
    return str(Path.home() / self.HISTORY_FILE)
AttributeError: type object 'Path' has no attribute 'home'
```

Following code is fine:
`return str(os.path.expanduser('~')+'/'+self.HISTORY_FILE)`

**Comment by davidbgk** [comment]
@cquest which version of Python are you using?

**Comment by davidbgk** [comment]
`Path.home()` has been [introduced in Python 3.5](https://docs.python.org/3/library/pathlib.html#pathlib.Path.home)

**Comment by cquest** [comment]
3.4... the alternative code is fine with 3.4 ;)
