### ISSUE TITLE
Unable to load data into Redis if using separated indexes & documents

### ISSUE THREAD

**Issue by ThomasG77** [addok/addok#303]
When I use this following config to separate indexes and documents, I'm now unable to load the data in Redis.

```
REDIS = {
    'host': 'localhost',
    'port': 6379,
    'indexes': {
        'db': 11,
    },
    'documents': {
        'db': 12,
    }
}

QUERY_PROCESSORS_PYPATHS = [
    "addok_france.extract_address",
    "addok_france.clean_query",
    "addok_france.remove_leading_zeros",
]
SEARCH_RESULT_PROCESSORS_PYPATHS = [
    "addok_france.match_housenumber",
    "addok_france.make_labels",
    "addok.helpers.results.score_by_importance",
    "addok.helpers.results.score_by_autocomplete_distance",
    "addok.helpers.results.score_by_ngram_distance",
    "addok.helpers.results.score_by_geo_distance",
]
PROCESSORS_PYPATHS = [
    "addok.helpers.text.tokenize",
    "addok.helpers.text.normalize",
    "addok_france.glue_ordinal",
    "addok_france.fold_ordinal",
    "addok_france.flag_housenumber",
    "addok.helpers.text.synonymize",
    "addok_fr.phonemicize",
]
```

The exact command line I've run is `/srv/addok/venv/bin/addok --config /etc/addok/addok.conf batch BAN_odbl.json`.

The traceback is the following
```
Loaded local config from /etc/addok/addok.conf
Traceback (most recent call last):
  File "/srv/addok/venv/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/bin/__init__.py", line 44, in main
    from addok.debug import Cli
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/debug.py", line 13, in <module>
    from .core import (Search, SearchResult, Token, compute_geohash_key,
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/core.py", line 7, in <module>
    from .db import DB
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/db.py", line 5, in <module>
    DB = redis.StrictRedis(**config.REDIS)
TypeError: __init__() got an unexpected keyword argument 'indexes'
```

The quick fix to the issue is to replace the REDIS part with the default
```
REDIS = {
    'host': 'localhost',
    'port': 6379,
    'db': 0
}
```

Are you able to reproduce?

**Comment by davidbgk** [comment]
Are you sure that you installed RC2? That line of code looks older, we now pass parameters explicitly.

**Comment by ThomasG77** [comment]
It seems I got an issue elsewhere. I will close the issue. Will reopen if it fails again.
