### ISSUE TITLE
Address regression in memory consumption across RCs

### ISSUE THREAD

**Issue by davidbgk** [addok/addok#315]
There was a failure on batch load of the whole BAN for devapi since the release of RC3.

Here is an attempt to reproduce and monitor the issue on a [6 x86 64bit Cores with 15Gb Scaleway server](https://www.scaleway.com/pricing/):

Count | RC2 (time) | RC2 (redis) | RC2 (htop redis) | RC3 (time) | RC3 (redis) | RC3 (htop redis)
------|------|-----| ------|-----|-----|----
286000 | 0:05:12 | 931 MB | 250Mb | 0:10:01 | 1055 MB | 1800Mb
500000 | 0:09:51 | 1787 MB | 3000Mb | 0:17:01 | 1532 MB | 3000Mb
1000000 | 0:26:01 | 3370 MB | 5500Mb | 0:30:54 | 3041 MB | 5400Mb
1189000 | | | | 0:36:21 | 4158 MB | 6500Mb
1243000 | 0:35:13 | 4190 MB | 7000Mb | | |

Both failed after 35 minutes, note that the processing time is not linear and neither is the memory consumption.

**Comment by davidbgk** [comment]
Error with RC2:

```
Processing… | Done: 1243000 | Elapsed: 0:35:13multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/index.py", line 69, in index_documents
    pipe.execute()
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2626, in execute
    return execute(conn, stack, raise_on_error)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2567, in _execute_pipeline
    self.raise_first_error(commands, response)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2574, in raise_first_error
    raise r
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2562, in _execute_pipeline
    self.parse_response(connection, args[0], **options))
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2584, in parse_response
    self, connection, command_name, **options)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/root/addok/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Command # 36585 (SADD p|46 en 60 limogn 46260 lila de oksitani lo ru 26 195 156 pirene midi kersi) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 65, in process_documents
    return list(iter_pipe(docs, config.BATCH_PROCESSORS))
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 31, in iter_pipe
    yield from pipe
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/index.py", line 72, in index_documents
    raise ValueError(msg)
ValueError: Error while importing document:
{'citycode': ['46173'], 'housenumbers': {'5145': {'lon': 1.771882, 'id': 'ADRNIVX_0000000283579236', 'x': 602188.4, 'lat': 44.397658, 'raw': '5145 F', 'y': 6367273.8}, 'f': {'lon': 1.771882, 'id': 'ADRNIVX_0000000283579236', 'x': 602188.4, 'lat': 44.397658, 'raw': '5145 F', 'y': 6367273.8}, '983': {'lon': 1.781352, 'id': 'ADRNIVX_0000000283579578', 'x': 602937, 'lat': 44.394382, 'raw': '983', 'y': 6366898.2}, '111': {'lon': 1.772533, 'id': 'ADRNIVX_0000000283579234', 'x': 602240.5, 'lat': 44.397811, 'raw': '111', 'y': 6367290}, 'ui': {'lon': 1.771129, 'id': 'ADRNIVX_0000000283579224', 'x': 602128.3, 'lat': 44.397557, 'raw': '8', 'y': 6367263.5}, '5340': {'lon': 1.771469, 'id': 'ADRNIVX_0000000283579237', 'x': 602155.4, 'lat': 44.397564, 'raw': '5340 F', 'y': 6367263.9}, 'neuf': {'lon': 1.771295, 'id': 'ADRNIVX_0000000283579225', 'x': 602141.6, 'lat': 44.397611, 'raw': '9', 'y': 6367269.3}, '522': {'lon': 1.776735, 'id': 'ADRNIVX_0000000310622387', 'x': 602571.7, 'lat': 44.395821, 'raw': '522', 'y': 6367063.7}, '82': {'lon': 1.772597, 'id': 'ADRNIVX_0000000283579233', 'x': 602245, 'lat': 44.397473, 'raw': '82', 'y': 6367252.3}, '963': {'lon': 1.781152, 'id': 'ADRNIVX_0000000310622388', 'x': 602920.7, 'lat': 44.394195, 'raw': '963', 'y': 6366877.7}, 'dix': {'lon': 1.771195, 'id': 'ADRNIVX_0000000283579226', 'x': 602133.5, 'lat': 44.397558, 'raw': '10', 'y': 6367263.5}, '30': {'lon': 1.771334, 'id': 'ADRNIVX_0000000283579229', 'x': 602144.6, 'lat': 44.39756, 'raw': '30', 'y': 6367263.6}, '419': {'lon': 1.775675, 'id': 'ADRNIVX_0000000283579611', 'x': 602488.8, 'lat': 44.396664, 'raw': '419', 'y': 6367158.7}, '81': {'lon': 1.772186, 'id': 'ADRNIVX_0000000283579232', 'x': 602212.6, 'lat': 44.397648, 'raw': '81', 'y': 6367272.3}, 'katorz': {'lon': 1.771145, 'id': 'ADRNIVX_0000000283579227', 'x': 602129.5, 'lat': 44.397546, 'raw': '14', 'y': 6367262.3}, '42': {'lon': 1.771618, 'id': 'ADRNIVX_0000000283579231', 'x': 602167.2, 'lat': 44.397571, 'raw': '42', 'y': 6367264.4}, '34': {'lon': 1.77153, 'id': 'ADRNIVX_0000000358567125', 'x': 602160, 'lat': 44.397451, 'raw': '34', 'y': 6367251.2}, '549': {'lon': 1.776882, 'id': 'ADRNIVX_0000000283579613', 'x': 602583.5, 'lat': 44.395852, 'raw': '549', 'y': 6367067}, '26': {'lon': 1.771375, 'id': 'ADRNIVX_0000000283579228', 'x': 602147.9, 'lat': 44.397564, 'raw': '26', 'y': 6367264}, '353': {'lon': 1.775112, 'id': 'ADRNIVX_0000000283579059', 'x': 602444.7, 'lat': 44.397095, 'raw': '353', 'y': 6367207.2}, '36': {'lon': 1.774702, 'id': 'ADRNIVX_0000000283579058', 'x': 602412.6, 'lat': 44.397447, 'raw': '36', 'y': 6367246.8}, 'dix ui': {'lon': 1.775528, 'id': 'ADRNIVX_0000000341045346', 'x': 602477.7, 'lat': 44.397029, 'raw': '18', 'y': 6367199.4}}, 'id': '46173_XXXX_eb02a4', 'lat': 44.397003, 'city': 'Limogne-en-Quercy', 'y': 6367198.7, 'importance': 0.1437, 'lon': 1.773735, 'type': 'street', 'postcode': '46260', 'x': 602334.8, 'context': '46, Lot, Occitanie (Midi-Pyrénées)', 'name': 'Avenue de Villefranche'}
Command # 36585 (SADD p|46 en 60 limogn 46260 lila de oksitani lo ru 26 195 156 pirene midi kersi) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/addok/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/root/addok/lib/python3.5/site-packages/addok/bin/__init__.py", line 27, in main
    args.func(args)
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 15, in run
    process_file(path)
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 48, in process_file
    batch(config.BATCH_FILE_LOADER(filepath))
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 71, in batch
    throttle=timedelta(seconds=1))
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 162, in parallelize
    for chunk in pool.imap_unordered(func, iterable, chunk_size):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
ValueError: Error while importing document:
{'citycode': ['46173'], 'housenumbers': {'5145': {'lon': 1.771882, 'id': 'ADRNIVX_0000000283579236', 'x': 602188.4, 'lat': 44.397658, 'raw': '5145 F', 'y': 6367273.8}, 'f': {'lon': 1.771882, 'id': 'ADRNIVX_0000000283579236', 'x': 602188.4, 'lat': 44.397658, 'raw': '5145 F', 'y': 6367273.8}, '983': {'lon': 1.781352, 'id': 'ADRNIVX_0000000283579578', 'x': 602937, 'lat': 44.394382, 'raw': '983', 'y': 6366898.2}, '111': {'lon': 1.772533, 'id': 'ADRNIVX_0000000283579234', 'x': 602240.5, 'lat': 44.397811, 'raw': '111', 'y': 6367290}, 'ui': {'lon': 1.771129, 'id': 'ADRNIVX_0000000283579224', 'x': 602128.3, 'lat': 44.397557, 'raw': '8', 'y': 6367263.5}, '5340': {'lon': 1.771469, 'id': 'ADRNIVX_0000000283579237', 'x': 602155.4, 'lat': 44.397564, 'raw': '5340 F', 'y': 6367263.9}, 'neuf': {'lon': 1.771295, 'id': 'ADRNIVX_0000000283579225', 'x': 602141.6, 'lat': 44.397611, 'raw': '9', 'y': 6367269.3}, '522': {'lon': 1.776735, 'id': 'ADRNIVX_0000000310622387', 'x': 602571.7, 'lat': 44.395821, 'raw': '522', 'y': 6367063.7}, '82': {'lon': 1.772597, 'id': 'ADRNIVX_0000000283579233', 'x': 602245, 'lat': 44.397473, 'raw': '82', 'y': 6367252.3}, '963': {'lon': 1.781152, 'id': 'ADRNIVX_0000000310622388', 'x': 602920.7, 'lat': 44.394195, 'raw': '963', 'y': 6366877.7}, 'dix': {'lon': 1.771195, 'id': 'ADRNIVX_0000000283579226', 'x': 602133.5, 'lat': 44.397558, 'raw': '10', 'y': 6367263.5}, '30': {'lon': 1.771334, 'id': 'ADRNIVX_0000000283579229', 'x': 602144.6, 'lat': 44.39756, 'raw': '30', 'y': 6367263.6}, '419': {'lon': 1.775675, 'id': 'ADRNIVX_0000000283579611', 'x': 602488.8, 'lat': 44.396664, 'raw': '419', 'y': 6367158.7}, '81': {'lon': 1.772186, 'id': 'ADRNIVX_0000000283579232', 'x': 602212.6, 'lat': 44.397648, 'raw': '81', 'y': 6367272.3}, 'katorz': {'lon': 1.771145, 'id': 'ADRNIVX_0000000283579227', 'x': 602129.5, 'lat': 44.397546, 'raw': '14', 'y': 6367262.3}, '42': {'lon': 1.771618, 'id': 'ADRNIVX_0000000283579231', 'x': 602167.2, 'lat': 44.397571, 'raw': '42', 'y': 6367264.4}, '34': {'lon': 1.77153, 'id': 'ADRNIVX_0000000358567125', 'x': 602160, 'lat': 44.397451, 'raw': '34', 'y': 6367251.2}, '549': {'lon': 1.776882, 'id': 'ADRNIVX_0000000283579613', 'x': 602583.5, 'lat': 44.395852, 'raw': '549', 'y': 6367067}, '26': {'lon': 1.771375, 'id': 'ADRNIVX_0000000283579228', 'x': 602147.9, 'lat': 44.397564, 'raw': '26', 'y': 6367264}, '353': {'lon': 1.775112, 'id': 'ADRNIVX_0000000283579059', 'x': 602444.7, 'lat': 44.397095, 'raw': '353', 'y': 6367207.2}, '36': {'lon': 1.774702, 'id': 'ADRNIVX_0000000283579058', 'x': 602412.6, 'lat': 44.397447, 'raw': '36', 'y': 6367246.8}, 'dix ui': {'lon': 1.775528, 'id': 'ADRNIVX_0000000341045346', 'x': 602477.7, 'lat': 44.397029, 'raw': '18', 'y': 6367199.4}}, 'id': '46173_XXXX_eb02a4', 'lat': 44.397003, 'city': 'Limogne-en-Quercy', 'y': 6367198.7, 'importance': 0.1437, 'lon': 1.773735, 'type': 'street', 'postcode': '46260', 'x': 602334.8, 'context': '46, Lot, Occitanie (Midi-Pyrénées)', 'name': 'Avenue de Villefranche'}
Command # 36585 (SADD p|46 en 60 limogn 46260 lila de oksitani lo ru 26 195 156 pirene midi kersi) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by davidbgk** [comment]
Error with RC3:

```
Processing… - Done: 1189000 | Elapsed: 0:36:21multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 65, in process_documents
    return list(iter_pipe(docs, config.BATCH_PROCESSORS))
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 31, in iter_pipe
    yield from pipe
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/index.py", line 57, in index_documents
    for doc in docs:
  File "/root/addok/lib/python3.5/site-packages/addok/ds.py", line 60, in store_documents
    doc['_id'] = DB.next_id()
  File "/root/addok/lib/python3.5/site-packages/addok/db.py", line 21, in next_id
    next_id = self.incr('_id_sequence')
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 915, in incr
    return self.execute_command('INCRBY', name, amount)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/root/addok/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/addok/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/root/addok/lib/python3.5/site-packages/addok/bin/__init__.py", line 30, in main
    args.func(args)
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 15, in run
    process_file(path)
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 48, in process_file
    batch(config.BATCH_FILE_LOADER(filepath))
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 71, in batch
    throttle=timedelta(seconds=1))
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 162, in parallelize
    for chunk in pool.imap_unordered(func, iterable, chunk_size):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by davidbgk** [comment]
Same Redis error on both failures:

```
14812:M 27 Mar 16:36:15.091 # Can't save in background: fork: Cannot allocate memory
```

**Comment by davidbgk** [comment]
Procedure to reproduce:

```
apt-get update
apt-get install redis-server sqlite python3.5 python3.5-dev python-pip python-virtualenv pbzip2
virtualenv addok --python=/usr/bin/python3.5
source addok/bin/activate
pip install addok==1.0.0rc.3 addok-sqlite-store==1.0.0rc.3 addok-csv==1.0.0rc.3 addok-france==1.0.0rc.3 addok-fr==1.0.0rc.3 httpie
# 42 sec:
http --download https://bano.openstreetmap.fr/BAN_odbl/BAN_odbl.json.bz2
# 5 min?
pbzip2 -d BAN_odbl.json.bz2

# elsewhere
redis-server

nano local.py
# Copy-paste:
QUERY_PROCESSORS_PYPATHS = [
    "addok_france.extract_address",
    "addok_france.clean_query",
    "addok_france.remove_leading_zeros",
    "addok_france.glue_ordinal",
    "addok_france.fold_ordinal",
]
HOUSENUMBER_PROCESSORS_PYPATHS = [
    "addok_france.remove_leading_zeros",
    "addok_france.glue_ordinal",
    "addok_france.fold_ordinal",
]
SEARCH_RESULT_PROCESSORS_PYPATHS = [
    "addok.helpers.results.match_housenumber",
    "addok_france.make_labels",
    "addok.helpers.results.score_by_importance",
    "addok.helpers.results.score_by_autocomplete_distance",
    "addok.helpers.results.score_by_ngram_distance",
    "addok.helpers.results.score_by_geo_distance",
]
PROCESSORS_PYPATHS = [
    "addok.helpers.text.tokenize",
    "addok.helpers.text.normalize",
    "addok.helpers.text.synonymize",
    "addok_fr.phonemicize",
]
# ctrl+o enter ctrl+x

export ADDOK_CONFIG_MODULE=/root/local.py

addok batch BAN_odbl.json
```

**Comment by davidbgk** [comment]
At the moment of the crash, the redis `dump.rdb` database was 1.1Gb in case of RC2 vs. 712Mb for RC3. The sqlite `addok.db` database was 866Mb in case of RC2 vs. 804Mb for RC3.

**Comment by davidbgk** [comment]
Taking a look at the [diff between RC2 and RC3](https://github.com/addok/addok/compare/addok:1.0.0-rc.2...addok:1.0.0-rc.3), it's either the hashids thing or the new way to deal with housenumbers.

But given that both versions failed to load the whole BAN dump, I'll retry with RC1…

**Comment by davidbgk** [comment]
New attempt, this time with RC1:

Count | RC1 (time) | RC1 (redis) | RC1 (htop redis) |  RC2 (time) | RC2 (redis) | RC2 (htop redis) | RC3 (time) | RC3 (redis) | RC3 (htop redis)
------|------|-----| ------|-----|-----|----|-----|-----|----
286000 | 0:02:41 | 996 MB | 1700Mb | 0:05:12 | 931 MB | 250Mb | 0:10:01 | 1055 MB | 1800Mb
500000 | 0:05:00 | 1890 MB | 2800Mb | 0:09:51 | 1787 MB | 3000Mb | 0:17:01 | 1532 MB | 3000Mb
1000000 | 0:09:41 | 3470 MB | 5200Mb | 0:26:01 | 3370 MB | 5500Mb | 0:30:54 | 3041 MB | 5400Mb
1189000 | | | | | | | 0:36:21 | 4158 MB | 6500Mb
1243000 | | | | 0:35:13 | 4190 MB | 7000Mb | | |
1448000 | 0:14:04 | 4902 MB | 7300 Mb | | | | | | |


Note: installation requires to get RC1 from github given #265 

```
apt-get install git
pip install --upgrade git+https://github.com/addok/addok.git@1.0.0-rc.1
```

**Comment by davidbgk** [comment]
Error with RC1:

```
Processing… / Done: 1448000 | Elapsed: 0:14:04multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/index.py", line 69, in index_documents
    pipe.execute()
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2626, in execute
    return execute(conn, stack, raise_on_error)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2567, in _execute_pipeline
    self.raise_first_error(commands, response)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2574, in raise_first_error
    raise r
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2562, in _execute_pipeline
    self.parse_response(connection, args[0], **options))
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 2584, in parse_response
    self, connection, command_name, **options)
  File "/root/addok/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/root/addok/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Command # 52411 (ZADD w|54210 1.0159 d|54483_0118_c5bcc3) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 75, in process_documents
    return list(iter_pipe(docs, config.DOCUMENT_PROCESSORS))
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 16, in iter_pipe
    yield from pipe
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/index.py", line 72, in index_documents
    raise ValueError(msg)
ValueError: Error while importing document:
{'type': 'street', 'lon': 6.054749, 'name': 'Allée des Merisiers', 'context': '54, Meurthe-et-Moselle, Grand-Est (Lorraine)', 'city': 'Saizerais', 'citycode': ['54490'], 'id': '54490_XXXX_95885c', 'y': 6859064.5, 'x': 924357.7, 'housenumbers': {'76': {'lon': 6.055108, 'id': 'ADRNIVX_0000000265829377', 'y': 6859040.1, 'x': 924385, 'lat': 48.792373, 'raw': '76'}, '71': {'lon': 6.054165, 'id': 'ADRNIVX_0000000265829372', 'y': 6859099.9, 'x': 924313.4, 'lat': 48.792935, 'raw': '71'}, '52': {'lon': 6.055112, 'id': 'ADRNIVX_0000000265829369', 'y': 6859046.3, 'x': 924385.1, 'lat': 48.792429, 'raw': '52'}, '53': {'lon': 6.055333, 'id': 'ADRNIVX_0000000265829370', 'y': 6859036.6, 'x': 924401.7, 'lat': 48.792336, 'raw': '53'}, '73': {'lon': 6.054511, 'id': 'ADRNIVX_0000000265829374', 'y': 6859071.5, 'x': 924339.9, 'lat': 48.792671, 'raw': '73'}, '74': {'lon': 6.054705, 'id': 'ADRNIVX_0000000265829375', 'y': 6859057.2, 'x': 924354.7, 'lat': 48.792537, 'raw': '74'}, '54': {'lon': 6.055566, 'id': 'ADRNIVX_0000000265829371', 'y': 6859026.8, 'x': 924419.2, 'lat': 48.792241, 'raw': '54'}, '50': {'lon': 6.05473, 'id': 'ADRNIVX_0000000265829367', 'y': 6859063.5, 'x': 924356.3, 'lat': 48.792593, 'raw': '50'}, '51': {'lon': 6.054902, 'id': 'ADRNIVX_0000000265829368', 'y': 6859054.9, 'x': 924369.3, 'lat': 48.792511, 'raw': '51'}, '48': {'lon': 6.054387, 'id': 'ADRNIVX_0000000265829365', 'y': 6859089.3, 'x': 924330.1, 'lat': 48.792834, 'raw': '48'}, '49': {'lon': 6.054531, 'id': 'ADRNIVX_0000000265829366', 'y': 6859077, 'x': 924341.2, 'lat': 48.79272, 'raw': '49'}, '47': {'lon': 6.054173, 'id': 'ADRNIVX_0000000265829364', 'y': 6859106.9, 'x': 924313.7, 'lat': 48.792998, 'raw': '47'}, '72': {'lon': 6.054348, 'id': 'ADRNIVX_0000000265829373', 'y': 6859084.9, 'x': 924327.4, 'lat': 48.792796, 'raw': '72'}, '75': {'lon': 6.054912, 'id': 'ADRNIVX_0000000265829376', 'y': 6859048.4, 'x': 924370.3, 'lat': 48.792453, 'raw': '75'}}, 'importance': 0.0183, 'lat': 48.792602, 'postcode': '54380'}
Command # 52411 (ZADD w|54210 1.0159 d|54483_0118_c5bcc3) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/addok/bin/addok", line 11, in <module>
    load_entry_point('addok==1.0.0rc1', 'console_scripts', 'addok')()
  File "/root/addok/lib/python3.5/site-packages/addok/bin/__init__.py", line 25, in main
    args.func(args)
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 15, in run
    process_file(path)
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 58, in process_file
    batch(preprocess_batch(f))
  File "/root/addok/lib/python3.5/site-packages/addok/batch.py", line 81, in batch
    throttle=timedelta(seconds=1))
  File "/root/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 151, in parallelize
    for chunk in pool.imap_unordered(func, iterable, chunk_size):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
ValueError: Error while importing document:
{'type': 'street', 'lon': 6.054749, 'name': 'Allée des Merisiers', 'context': '54, Meurthe-et-Moselle, Grand-Est (Lorraine)', 'city': 'Saizerais', 'citycode': ['54490'], 'id': '54490_XXXX_95885c', 'y': 6859064.5, 'x': 924357.7, 'housenumbers': {'76': {'lon': 6.055108, 'id': 'ADRNIVX_0000000265829377', 'y': 6859040.1, 'x': 924385, 'lat': 48.792373, 'raw': '76'}, '71': {'lon': 6.054165, 'id': 'ADRNIVX_0000000265829372', 'y': 6859099.9, 'x': 924313.4, 'lat': 48.792935, 'raw': '71'}, '52': {'lon': 6.055112, 'id': 'ADRNIVX_0000000265829369', 'y': 6859046.3, 'x': 924385.1, 'lat': 48.792429, 'raw': '52'}, '53': {'lon': 6.055333, 'id': 'ADRNIVX_0000000265829370', 'y': 6859036.6, 'x': 924401.7, 'lat': 48.792336, 'raw': '53'}, '73': {'lon': 6.054511, 'id': 'ADRNIVX_0000000265829374', 'y': 6859071.5, 'x': 924339.9, 'lat': 48.792671, 'raw': '73'}, '74': {'lon': 6.054705, 'id': 'ADRNIVX_0000000265829375', 'y': 6859057.2, 'x': 924354.7, 'lat': 48.792537, 'raw': '74'}, '54': {'lon': 6.055566, 'id': 'ADRNIVX_0000000265829371', 'y': 6859026.8, 'x': 924419.2, 'lat': 48.792241, 'raw': '54'}, '50': {'lon': 6.05473, 'id': 'ADRNIVX_0000000265829367', 'y': 6859063.5, 'x': 924356.3, 'lat': 48.792593, 'raw': '50'}, '51': {'lon': 6.054902, 'id': 'ADRNIVX_0000000265829368', 'y': 6859054.9, 'x': 924369.3, 'lat': 48.792511, 'raw': '51'}, '48': {'lon': 6.054387, 'id': 'ADRNIVX_0000000265829365', 'y': 6859089.3, 'x': 924330.1, 'lat': 48.792834, 'raw': '48'}, '49': {'lon': 6.054531, 'id': 'ADRNIVX_0000000265829366', 'y': 6859077, 'x': 924341.2, 'lat': 48.79272, 'raw': '49'}, '47': {'lon': 6.054173, 'id': 'ADRNIVX_0000000265829364', 'y': 6859106.9, 'x': 924313.7, 'lat': 48.792998, 'raw': '47'}, '72': {'lon': 6.054348, 'id': 'ADRNIVX_0000000265829373', 'y': 6859084.9, 'x': 924327.4, 'lat': 48.792796, 'raw': '72'}, '75': {'lon': 6.054912, 'id': 'ADRNIVX_0000000265829376', 'y': 6859048.4, 'x': 924370.3, 'lat': 48.792453, 'raw': '75'}}, 'importance': 0.0183, 'lat': 48.792602, 'postcode': '54380'}
Command # 52411 (ZADD w|54210 1.0159 d|54483_0118_c5bcc3) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by davidbgk** [comment]
My interpretation so far is that we introduce a major drop into performances [from RC1 to RC2](https://github.com/addok/addok/compare/addok:1.0.0-rc.1...addok:1.0.0-rc.2) that might be caused by the way we refactored housenumbers pairing.

We can probably gain some speed with RC3 but it crashes before we can evaluate that. It will definitely not be at the same magnitude of the drop introduced by RC2.

Second conclusion: it is not possible to load the BAN on a 15Gb server whatever the RC 😞 .

Next step: try with a 30Gb one! 👍

**Comment by davidbgk** [comment]
Alright, this time same provider but with a 8 x86 64bit Cores 30GB memory server:

Count | RC1 (time) | RC1 (redis) | RC1 (htop redis) |  RC2 (time) | RC2 (redis) | RC2 (htop redis) | RC3 (time) | RC3 (redis) | RC3 (htop redis)
------|------|-----| ------|-----|-----|----|-----|-----|----
286000 |  |  |  |  |  |  | 0:03:16 | 927 MB | 1800Mb
500000 |  |  |  |  |  |  | 0:05:59 | 1750 MB | 3000Mb
1000000 |  |  |  |  |  |  | 0:12:31 | 3679 MB | 5500Mb
1500000 |  |  |  |  |  |  | 0:19:40 | 5684 MB | 8200Mb
2000000 |  |  |  |  |  |  | 0:28:25 | 7757 MB | 10.8Gb
2444894 |  |  |  |  |  |  | 0:35:55 | 9234 MB | 13.3Gb

**Comment by davidbgk** [comment]
Once everything is loaded, the `addok.db` file is 1.7Gb and the `dump.rdb` one is 1.5Gb.

**Comment by davidbgk** [comment]
After giving it a try without saving on disk, the RC3 failed close to the end by lack of memory:
```
Processing… \ Done: 2174000 | Elapsed: 0:48:00multiprocessing.pool.RemoteTraceback:
```

One option is to set `overcommit_memory` to `1` as proposed by Redis on launch:
```
WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

I'm pretty sure that making Redis swap is a bad idea but it might be relevant just for the short period of the batch import.

**Comment by davidbgk** [comment]
Even with that option it doesn't finish and Redis dies… 😭

**Comment by davidbgk** [comment]
With RC1 it crashes at 2371000 after 40 minutes so we were able to index 200000 more docs on the same configuration vs. RC3. We're very close to be able to do it on a 15Gb server but I would not recommend it anyway given how close it is to a segmentation fault on Redis side.

We should recommend a 30Gb server in the documentation and at least have 20 if we want a minimal setup with the `redis-cli save` at the end.
