### ISSUE TITLE
Crash when importing with default addok.conf (match_housenumber)

### ISSUE THREAD

**Issue by alfredott** [addok/addok#337]
Hello

I've just installed addok, following this tutorial : http://addok.readthedocs.io/fr/master-b00b342-fr/tutorial/

When I try to import my data (with "addok batch my_file.json")), "addok batch" crashes, and returns the following error stack trace : 

>Addok 1.0.0
Loaded local config from /etc/addok/addok.conf
Traceback (most recent call last):
  File "/home/server/addok/bin/addok", line 11, in <module>
    load_entry_point('addok==1.0.0', 'console_scripts', 'addok')()
  File "/home/server/addok/lib/python3.4/site-packages/addok/bin/__init__.py", line 26, in main
    config.load()
  File "/home/server/addok/lib/python3.4/site-packages/addok/config/__init__.py", line 43, in load
    self.resolve()
  File "/home/server/addok/lib/python3.4/site-packages/addok/config/__init__.py", line 115, in resolve
    self.resolve_paths(key)
  File "/home/server/addok/lib/python3.4/site-packages/addok/config/__init__.py", line 126, in resolve_paths
    for path in self[key]]
  File "/home/server/addok/lib/python3.4/site-packages/addok/config/__init__.py", line 126, in <listcomp>
    for path in self[key]]
  File "/home/server/addok/lib/python3.4/site-packages/addok/helpers/__init__.py", line 44, in import_by_path
    func = getattr(func, name[0])
AttributeError: 'module' object has no attribute 'match_housenumber'

I noticed that commenting the line ""addok_france.match_housenumber"," in /etc/addok/addok.conf" prevents the import from crashing. Then, I can use "addok shell" normally, but there are no house numbers in search results.( i.e : removing this line in the addok.conf file just makes addok not handle house numbers.)

Is this problem normal ? Am I the only one to face it ?

PS : I have tried with both BAN_odbl.json and BAN_odbl_92-json, and as you can see, I'm using Python3.4.

Bye

**Comment by davidbgk** [comment]
Hello,

The translated documentation is not up-to-date, please refer to http://addok.readthedocs.io/en/latest/tutorial/#create-a-local-configuration-file which link to the right `match_housenumbers` path.

**Comment by alfredott** [comment]
Thanks,

It works properly now
