### ISSUE TITLE
WRONGTYPE Operation against a key holding the wrong kind of value with only common and lon/lat

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#340]
```
Traceback (most recent call last):
  File "/srv/addok/venv/lib/python3.4/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/http/base.py", line 134, in on_get
    lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 327, in search
    return helper(query, lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 167, in __call__
    if collector(self):
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/collectors.py", line 48, in only_commons
    ids = scripts.manual_scan(keys=keys, args=[helper.wanted])
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_0804d6ddda0bf738fb5956006dc66bb64456ea7a): @user_script:18: WRONGTYPE Operation against a key holding the wrong kind of value 
[pid: 1534|app: 0|req: 44461/176949] 151.80.102.135 () {32 vars in 559 bytes} [Fri May  5 08:56:59 2017] GET /search/?f=json&q=rue+de+l&limit=10&lat=49.11&lon=7.0675&type=street&citycode= => generated 0 bytes in 4 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by yohanboniface** [comment]
```
Traceback (most recent call last):
  File "/srv/addok/venv/lib/python3.4/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/http/base.py", line 134, in on_get
    lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 327, in search
    return helper(query, lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 167, in __call__
    if collector(self):
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/collectors.py", line 48, in only_commons
    ids = scripts.manual_scan(keys=keys, args=[helper.wanted])
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/srv/addok/venv/lib/python3.4/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_0804d6ddda0bf738fb5956006dc66bb64456ea7a): @user_script:18: WRONGTYPE Operation against a key holding the wrong kind of value 
[pid: 1534|app: 0|req: 44422/176764] 149.6.164.54 () {48 vars in 787 bytes} [Fri May  5 08:55:34 2017] GET /search/?limit=10&q=43+route+d+&type=housenumber => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on 
core 0)
```
