### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid distance too far back

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#341]
```
Traceback (most recent call last):
  File "/srv/addok/venv/lib/python3.4/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/http/base.py", line 134, in on_get
    lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 327, in search
    return helper(query, lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 167, in __call__
    if collector(self):
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/fuzzy.py", line 42, in fuzzy_collector
    if helper.fuzzy and not helper.has_cream():
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 262, in has_cream
    self.convert()
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 227, in convert
    for _id, doc in documents:
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/ds.py", line 84, in get_documents
    yield id_, config.DOCUMENT_SERIALIZER.loads(blob)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/serializers.py", line 13, in loads
    return json.loads(zlib.decompress(data).decode())
zlib.error: Error -3 while decompressing data: invalid distance too far back
```

**Comment by jdesboeufs** [comment]
We need more context. As it’s old, I close.
