### ISSUE TITLE
sqlite-store: "sqlite3.DatabaseError: database disk image is malformed" under heavy load

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#343]
```
Traceback (most recent call last):
  File "/srv/addok/venv/lib/python3.5/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/http/base.py", line 134, in on_get
    lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/core.py", line 327, in search
    return helper(query, lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/core.py", line 167, in __call__
    if collector(self):
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/fuzzy.py", line 42, in fuzzy_collector
    if helper.fuzzy and not helper.has_cream():
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/core.py", line 262, in has_cream
    self.convert()
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/core.py", line 227, in convert
    for _id, doc in documents:
  File "/srv/addok/venv/lib/python3.5/site-packages/addok/ds.py", line 83, in get_documents
    for id_, blob in DS.fetch(*keys):
  File "/srv/addok/venv/lib/python3.5/site-packages/addok_sqlite_store/__init__.py", line 30, in fetch
    cursor = conn.execute(query, keys)
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by yohanboniface** [comment]
Fixed by configuring uwsgi not to fork:

`lazy-apps = true` in the configuration.

Means uwsgi will create each process and load the python app, instead of loading the python app and forking for each process (shared pointers, thus share sqlite connection).
