### ISSUE TITLE
addok-csv: AttributeError: 'str' object has no attribute 'file'

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#344]
```
Traceback (most recent call last):
  File "/srv/addok/venv/lib/python3.4/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_csv/__init__.py", line 123, in on_post
    content = self.compute_content(req, file_, encoding)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_csv/__init__.py", line 37, in compute_content
    content = file_.file.read().decode(encoding)
AttributeError: 'str' object has no attribute 'file'
Traceback (most recent call last):
  File "/srv/addok/venv/lib/python3.4/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_csv/__init__.py", line 123, in on_post
    content = self.compute_content(req, file_, encoding)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_csv/__init__.py", line 37, in compute_content
    content = file_.file.read().decode(encoding)
AttributeError: 'str' object has no attribute 'file'
```

May be linked to how uwsgi parse the request…

**Comment by davidbgk** [comment]
Same as https://github.com/addok/addok/issues/342
