### ISSUE TITLE
Rechercher avec le plugin addok-france

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#357]
J'ai un plantage lorsque je fais la recherche suivante: `/search/?q=011T`

L'erreur est la suivante (addok shell) :

```
Traceback (most recent call last):
  File "/srv/addok/venv/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/bin/__init__.py", line 25, in main
    args.func(args)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/shell.py", line 489, in invoke
    cmd.loop()
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/shell.py", line 72, in loop
    self.cmdloop()
  File "/usr/lib64/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/shell.py", line 194, in do_SEARCH
    self._search(query)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/shell.py", line 164, in _search
    results = helper(query, lat=lat, lon=lon, **filters)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/core.py", line 160, in __call__
    func(self)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/search.py", line 12, in tokenize
    helper.tokens = preprocess_query(helper.query)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/search.py", line 8, in preprocess_query
    return list(iter_pipe(s, config.QUERY_PROCESSORS + config.PROCESSORS))
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/__init__.py", line 16, in iter_pipe
    yield from pipe
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/__init__.py", line 36, in wrapper
    for item in pipe:
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/__init__.py", line 36, in wrapper
    for item in pipe:
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_france/utils.py", line 109, in flag_housenumber
    for previous, token, next_ in neighborhood(tokens):
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_france/utils.py", line 80, in neighborhood
    current = next(iterator)  # Throws StopIteration if empty.
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/__init__.py", line 36, in wrapper
    for item in pipe:
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_france/utils.py", line 90, in glue_ordinal
    for _, token, next_ in neighborhood(tokens):
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_france/utils.py", line 80, in neighborhood
    current = next(iterator)  # Throws StopIteration if empty.
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/__init__.py", line 36, in wrapper
    for item in pipe:
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/text.py", line 66, in tokenize
    for text in pipe:
  File "/srv/addok/venv/lib/python3.4/site-packages/addok/helpers/__init__.py", line 37, in wrapper
    yield func(item)
  File "/srv/addok/venv/lib/python3.4/site-packages/addok_france/utils.py", line 124, in fold_ordinal
    s = s.update('{}{}'.format(number,
AttributeError: 'str' object has no attribute 'update'
```

Il semble qu'un cas ne soit pas géré dans le plugin `addok-france` : https://github.com/addok/addok-france/blob/master/addok_france/utils.py#L125-L126

**Comment by yohanboniface** [comment]
Tu peux partager ta config steup?

**Comment by gdrouet** [comment]
```
HOUSENUMBERS_PAYLOAD_FIELDS = ['hexacleNumber']

QUERY_PROCESSORS_PYPATHS = [
    "addok_france.extract_address",
    "addok_france.clean_query",
    "addok_france.remove_leading_zeros",
    "addok_france.glue_ordinal",
    "addok_france.fold_ordinal",
]
SEARCH_RESULT_PROCESSORS_PYPATHS = [
    "addok_france.make_labels",
    "addok.helpers.results.score_by_importance",
    "addok.helpers.results.score_by_autocomplete_distance",
    "addok.helpers.results.score_by_ngram_distance",
    "addok.helpers.results.score_by_geo_distance",
    "addok.helpers.results.match_housenumber",
]
PROCESSORS_PYPATHS = [
    "addok.helpers.text.tokenize",
    "addok.helpers.text.normalize",
    "addok_france.glue_ordinal",
    "addok_france.fold_ordinal",
    "addok_france.flag_housenumber",
    "addok.helpers.text.synonymize",
    "addok_fr.phonemicize",
]

REDIS = {
    'host': 'xxx',
    'port': 6379,
    'db': 0
}
```

**Comment by yohanboniface** [comment]
Can you change `QUERY_PROCESSORS_PYPATHS` to

```
QUERY_PROCESSORS_PYPATHS = [
    "addok.helpers.text.check_query_length",
    "addok_france.extract_address",
    "addok_france.clean_query",
    "addok_france.remove_leading_zeros",
]
```
And try again (no need to reimport, this setting is only used on query time).

Side note: `match_housenumber` is missing from `SEARCH_RESULT_PROCESSORS_PYPATHS`, not sure if it's on purpose.

Also note that `HOUSENUMBERS_PAYLOAD_FIELDS` is now useless: every key in the hosuenumber payload will be honored.

See the [tutorial](http://addok.readthedocs.io/en/latest/tutorial/#create-a-local-configuration-file) for an up to date French config.

**Comment by gdrouet** [comment]
Thanks it fixes the issue. You can close it.
I confirm that `HOUSENUMBERS_PAYLOAD_FIELDS` can be removed now.
`addok.helpers.results.match_housenumber` is already added at last position.

**Comment by yohanboniface** [comment]
>  addok.helpers.results.match_housenumber is already added at last position.

If you add it after `make_label`, it means no label with housenumber will be created, and thus you scores will housenumbers will be lower.

**Comment by gdrouet** [comment]
Oh ok thank you
