### ISSUE TITLE
Internal Server Error - AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#364]
From last addok.

```
$ http --timeout 99999999 -f POST $HOST/search/csv/ columns='code postal' columns='ville' citycode='code insee' lat='dep_lat' lon='dep_lon' type='municipality' data@panneaux-election-batch2.csvh
```

```
[2017-05-23 17:48:40 +0200] [20872] [ERROR] Error handling request /search/csv/
Traceback (most recent call last):
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/falcon/api.py", line 227, in __call__
    responder(req, resp, **params)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/addok_csv/__init__.py", line 134, in on_post
    self.process_rows(req, writer, rows, filters, columns)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/addok_csv/__init__.py", line 114, in process_rows
    self.process_row(req, row, filters, columns)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/addok_csv/__init__.py", line 185, in process_row
    results = search(q, autocomplete=False, limit=1, **filters)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/addok/core.py", line 332, in search
    return helper(query, lat=lat, lon=lon, **filters)
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/addok/core.py", line 156, in __call__
    for k, v in filters.items() if v.strip()]
  File "/home/frodrigo/addok/addok/lib/python3.4/site-packages/addok/core.py", line 156, in <listcomp>
    for k, v in filters.items() if v.strip()]
AttributeError: 'NoneType' object has no attribute 'strip'
```

[panneaux-election-batch2.txt](https://github.com/addok/addok/files/1022789/panneaux-election-batch2.txt)

**Comment by frodrigo** [comment]
After reading the code I understand that the value of type field must an existing column in the CSV. Not obvious at all.
