### ISSUE TITLE
Problems among installation

### ISSUE THREAD

**Issue by boilfire** [addok/addok#367]
Hey i try to install addok with the use of tutorial from docs and when i am going to give the command addok --help i have the following messages.

Traceback (most recent call last):
  File "/srv/addok//.local/bin/addok", line 7, in <module>
    from addok.bin import main
  File "/srv/addok/.local/lib/python2.7/site-packages/addok/bin/__init__.py", line 7, in <module>
    from addok.config import config
  File "/srv/addok/.local/lib/python2.7/site-packages/addok/config/__init__.py", line 11, in <module>
    from . import default
  File "/srv/addok/.local/lib/python2.7/site-packages/addok/config/default.py", line 67, in <module>
    BATCH_WORKERS = os.cpu_count() - 1
AttributeError: 'module' object has no attribute 'cpu_count'

**Comment by davidbgk** [comment]
You must use Python 3.
