### ISSUE TITLE
error installation sur ubuntu16.04

### ISSUE THREAD

**Issue by DSqiansun** [addok/addok#522]
Bonjour,

j'ai essayé d'installer addok sur ma machine ubuntu16.04.
J'ai rencontré un problème, est ce que vous pouvez m'aider svp? 

(addok) qian@xps:~$ addok batch BAN_odbl_93-json
Addok 1.0.2
Loaded local config from /etc/addok/addok.conf
Traceback (most recent call last):
  File "/home/qian/addok/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/home/qian/addok/lib/python3.5/site-packages/addok/bin/__init__.py", line 26, in main
    config.load()
  File "/home/qian/addok/lib/python3.5/site-packages/addok/config/__init__.py", line 43, in load
    self.resolve()
  File "/home/qian/addok/lib/python3.5/site-packages/addok/config/__init__.py", line 115, in resolve
    self.resolve_paths(key)
  File "/home/qian/addok/lib/python3.5/site-packages/addok/config/__init__.py", line 126, in resolve_paths
    for path in self[key]]
  File "/home/qian/addok/lib/python3.5/site-packages/addok/config/__init__.py", line 126, in <listcomp>
    for path in self[key]]
  File "/home/qian/addok/lib/python3.5/site-packages/addok/helpers/__init__.py", line 44, in import_by_path
    func = getattr(func, name[0])
AttributeError: module 'addok.helpers.results' has no attribute 'score_by_str_distance'

Merci

**Comment by yohanboniface** [comment]
Je pense que la doc est à jour sur le master, pas sur la version stable :/
Essaie de remplace `score_by_str_distance` par `score_by_ngram_distance` dans la conf.

**Comment by DSqiansun** [comment]
D'accord, merci 
J'ai un autre error: AttributeError: module 'addok.helpers.results' has no attribute 'adjust_scores'

**Comment by DSqiansun** [comment]
Oui, j'ai installé le master, c'est ok! merci!:)
Sinon, si possible d'installer en Windows aussi?

Merci d'avance

**Comment by cquest** [comment]
Redis (dont addok dépend largement) n'est il me semble pas officiellement supporté sur Windows.
A éviter.
