### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by louia** [addok/addok#551]
Voici l'erreur que j'obtiens sous windows 10 avec Docker Desktop.

Que faire?

```addok_1        | [2019-05-04 16:03:00 +0000] [16] [ERROR] Error handling request /search?q=paris
addok_1        | Traceback (most recent call last):
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
addok_1        |     sock = self._connect()
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 511, in _connect
addok_1        |     socket.SOCK_STREAM):
addok_1        |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
addok_1        |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
addok_1        | socket.gaierror: [Errno -5] No address associated with hostname
addok_1        |
addok_1        | During handling of the above exception, another exception occurred:
addok_1        |
addok_1        | Traceback (most recent call last):
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
addok_1        |     connection.send_command(*args)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
addok_1        |     self.send_packed_command(self.pack_command(*args))
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
addok_1        |     self.connect()
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
addok_1        |     raise ConnectionError(self._error_message(e))
addok_1        | redis.exceptions.ConnectionError: Error -5 connecting to redis:6379. No address associated with hostname.
addok_1        |
addok_1        | During handling of the above exception, another exception occurred:
addok_1        |
addok_1        | Traceback (most recent call last):
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
addok_1        |     sock = self._connect()
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 511, in _connect
addok_1        |     socket.SOCK_STREAM):
addok_1        |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
addok_1        |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
addok_1        | socket.gaierror: [Errno -5] No address associated with hostname
addok_1        |
addok_1        | During handling of the above exception, another exception occurred:
addok_1        |
addok_1        | Traceback (most recent call last):
addok_1        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
addok_1        |     self.handle_request(listener, req, client, addr)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
addok_1        |     respiter = self.wsgi(environ, resp.start_response)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 227, in __call__
addok_1        |     responder(req, resp, **params)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/addok/http/base.py", line 134, in on_get
addok_1        |     lat=lat, lon=lon, **filters)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 331, in search
addok_1        |     return helper(query, lat=lat, lon=lon, **filters)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 158, in __call__
addok_1        |     func(self)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/addok/helpers/search.py", line 21, in search_tokens
addok_1        |     token.search()
addok_1        |   File "/usr/local/lib/python3.6/site-packages/addok/helpers/text.py", line 47, in search
addok_1        |     if DB.exists(self.key):
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 951, in exists
addok_1        |     return self.execute_command('EXISTS', name)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
addok_1        |     connection.send_command(*args)
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
addok_1        |     self.send_packed_command(self.pack_command(*args))
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
addok_1        |     self.connect()
addok_1        |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
addok_1        |     raise ConnectionError(self._error_message(e))
addok_1        | redis.exceptions.ConnectionError: Error -5 connecting to redis:6379. No address associated with hostname.
addok_1        | Loaded local config from /etc/addok/addok.patched.conf
addok_1        | Loaded plugins:
addok_1        | addok.shell==1.0.2, addok.http.base==1.0.2, addok.batch==1.0.2, addok.pairs==1.0.2, addok.fuzzy==1.0.2, addok.autocomplete==1.0.2, sqlite-store==1.0.0, france==1.1.0, fr==1.0.1, csv==1.0.1
addok_1        | 172.18.0.1 - - [04/May/2019:16:03:00 +0000] "GET /search?q=paris HTTP/1.1" 500 0 "-" "-"```

**Comment by krowix** [comment]
`redis.exceptions.ConnectionError: Error -5 connecting to redis:6379. No address associated with hostname.`

`redis` ne semble pas etre un nom de machine connue

**Comment by louia** [comment]
j'utilise en réalité ici le container Docker développé par le gouvernement français   > https://github.com/etalab/addok-docker
c'est assez étrange

**Comment by yohanboniface** [comment]
C'est clairement Redis qui n'est pas joignable. On peut pas faire grand-chose ici, mais ouvre peut-être un ticket sur le repo addok-docker.
