### ISSUE TITLE
bash: venv/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by mealinux** [addok/addok#553]
What will i do?
```
root@map-1:~# source venv/bin/activate
bash: venv/bin/activate: No such file or directory
```

**Comment by arya312** [comment]
I am facing the same issue, I have tried all these commands, it is still showing no such directory.

**Comment by igor-santo** [comment]
I ran this command `python3 -m venv path / to / venv` so I had to go back to `cd venv env `- after that the command `venv / bin / activate` worked

**Comment by igor-santo** [comment]
> I am facing the same issue, I have tried all these commands, it is still showing no such directory.

Check my comment bellow

**Comment by MystikIncarnate** [comment]
I faced this issue as well, while following https://netbox.readthedocs.io/en/stable/installation/3-netbox/

After following @igor-santo 's instructions I was able to create the files required, however hit this problem with the next step:

(venv) root@netbox:/opt/netbox/netbox# python3 manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

Looks like the docs need some fixing.  Following the official instructions and can't complete the process.  I cloned my install from git (rather than downloading an archive).

Not sure what to do now.

**Comment by MystikIncarnate** [comment]
I followed the rabbit hole of pip install, and kept installing whatever was listed as "no module named x" via pip install, and got down to this error....

```
# python3 manage.py createsuperuser

You have 46 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, sessions, taggit, tenancy, users, virtualization.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 100, in handle
    default_username = get_default_username(database=database)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/management/__init__.py", line 141, in get_default_username
    auth_app.User._default_manager.db_manager(database).get(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
```

Any suggestions from the team?  Stuck on Step 3 - install SuperUser from the guide here:
https://netbox.readthedocs.io/en/stable/installation/3-netbox/

**Comment by igor-santo** [comment]
> I faced this issue as well, while following https://netbox.readthedocs.io/en/stable/installation/3-netbox/
> 
> After following @igor-santo 's instructions I was able to create the files required, however hit this problem with the next step:
> 
> (venv) root@netbox:/opt/netbox/netbox# python3 manage.py createsuperuser Traceback (most recent call last): File "manage.py", line 8, in from django.core.management import execute_from_command_line ModuleNotFoundError: No module named 'django'
> 
> Looks like the docs need some fixing. Following the official instructions and can't complete the process. I cloned my install from git (rather than downloading an archive).
> 
> Not sure what to do now.

@MystikIncarnate have you tried using this same command giving the manage.py file path?

I had some issues similar to yours and I resolved it by simply putting the full reference.

**Comment by MystikIncarnate** [comment]
@igor-santo I had not but I tried just a few moments ago, resulting in the exact same error.

I'll leave the error text here in case it's actually different and I missed something.

```
(venv) root@netbox:/opt/netbox/netbox# python3 /opt/netbox/netbox/manage.py createsuperuser

You have 46 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, sessions, taggit, tenancy, users, virtualization.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 100, in handle
    default_username = get_default_username(database=database)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/management/__init__.py", line 141, in get_default_username
    auth_app.User._default_manager.db_manager(database).get(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

```

The carat, which may not translate very well on this, is under the quotation mark after FROM; the last quotation mark on the last line.

**Comment by yohanboniface** [comment]
How is netbox related to addok ?

**Comment by MystikIncarnate** [comment]
I'm confused by that comment. I've been following the netbox install guide (as linked).  Would it not be a netbox issue if I'm following the instructions to install netbox, and I'm unable to complete the process with the instructions provided?

Or are you implying that those are not the correct instructions?  I'm lost.

**Comment by MystikIncarnate** [comment]
Thank you for the clarification. I seem to be turned around. I ended up here from a google search and incorrectly assumed this was related to netbox. that's my fault.

To directly answer your question, I'm trying to get netbox installed on a new system; I realize now that this is probably not the right place to ask this question.  I appreciate you taking the time to make me aware of my error.  I will try to find a more relevant place to inquire about my issue.

Have a great day.

**Comment by RaptorialThing** [comment]
I did sudo apt-get install python3.7-venv
and python3.7 -m venv myenvname
and then source myenvname/bin/activate no  file (there are only 2 folders lib and include)

To fix that I did sudo apt-get install python3-venv
and python 3 -m venv myenvname
and then source myenvname/bin/activate works good (enter into virtual environment)

**Comment by gabrielmanoel-hub** [comment]
Utilizei esse caminho. 
$ source venv/Scripts/activate

**Comment by pydjdev78** [comment]
interpreter changing in vscode(press f1, then type python: select interpreter) solved my following issue. those who are facing similar following issue : i have fixed a problem( vscode wsl and bash terminal was showing /venv/scripts/activate: no such file or directory error. so wsl and bash terminal was not working.) by changing python interpreter to c:\Program Files\Python310\python.exe from vscode auto created \venv\scripts\python.exe.

i think you can also solve this problem by activating virtual environment created by you.

**Comment by nikunjsonule** [comment]
> Utilizei esse caminho. $ source venv/Scripts/activate

Obviously it work but the question is we want with 'bin' not with 'scripts'

**Comment by wjj28** [comment]
I had the same issue but after following [stackoverflow](https://stackoverflow.com/questions/69594088/error-when-creating-venv-error-command-im-ensurepip-upgrade-def)
On Ubuntu first, install the venv of the specific python version sudo apt install python3.9-venv

python3.9 -m venv myenv //specify the python version. This will create the virtual env "myenv"

**Comment by saladandonionrings** [comment]
what worked for me :
`pip install colorlog`

**Comment by constantinethegr8** [comment]
> What will i do?
> 
> ```
> root@map-1:~# source venv/bin/activate
> bash: venv/bin/activate: No such file or directory
> ```
```
!pip3 install virtualenv
!virtualenv my_venv

!source my_venv/bin/activate
!source my_venv/bin/activate; pip or something
```

**Comment by zapadalabz** [comment]
I'm not sure if this is correct, by I checked the venv directory and activate was in the Scripts folder, not bin.

source venv/Scripts/activate works for me

**Comment by cc2551010** [comment]
I think for Option 2, the third step needs to be changed from:

source path/to/theHarvester-venv/bin/activate

to:

source path/to/create/theHarvester-venv/bin/activate

**Comment by Javier32** [comment]
> 

This worked for me, thank you!

**Comment by Peneh1** [comment]
> I'm not sure if this is correct, but I checked the venv directory and activate was in the Scripts folder, not bin.
> 
> source venv/Scripts/activate works for me

Worked for me as I am using bash on Windows OS

**Comment by KazemDolatabadi** [comment]
first go to the path where env is there and make again env folder:
mkdir env
you will get this error: mkdir: cannot create directory ‘env’: File exists. It is ok!
then go to project root and:
source env/Scripts/activate
this worked for me

**Comment by Strexas** [comment]
creting .venv folder instead of venv, solved my issue.

**Comment by NameUserIII** [comment]
> creating `.venv` folder instead of `venv` solved my issue.

Thank you, it helpd me to install it on linux as well.
I modified file setup.sh line 61 to VENV_DIR=".venv"
