### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by theAlinux** [addok/addok#554]
run this command `addok batch BAN_odbl_93-json`

**output:**

```
Traceback (most recent call last):
  File "/usr/local/bin/addok", line 7, in <module>
    from addok.bin import main
  File "/usr/local/lib/python2.7/dist-packages/addok/bin/__init__.py", line 7, in <module>
    from addok.config import config
  File "/usr/local/lib/python2.7/dist-packages/addok/config/__init__.py", line 11, in <module>
    from . import default
  File "/usr/local/lib/python2.7/dist-packages/addok/config/default.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

**Comment by theAlinux** [comment]
hmm, there is docker, good
alright, there is api for UK, housenumbers, full address, postal code etc.

**Comment by theAlinux** [comment]
hmm, there is docker, good
alright, Is there api for UK, housenumbers, full address, postal code etc.

**Comment by theAlinux** [comment]
```
root@map-1:~# source venv/bin/activate
bash: source: venv/bin/activate: is a directory
```
???
