### ISSUE TITLE
Souci d'installation Redis

### ISSUE THREAD

**Issue by Stan92** [addok/addok#601]
Bonjour,

J'ai suivi le tuto pour installer Addok sur Ubuntu 18.04 (https://addok.readthedocs.io/en/latest/tutorial/#tutorial)

J'obtiens ce message d'erreur lié apparemment à Redis.
Malgré tout les services ont l'air de fonctionné mais du coup je ne sais pas si l'install est optimale.

```

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/srv/addok/venv/lib/python3.6/site-packages/addok/batch.py", line 65, in process_documents
return list(iter_pipe(docs, config.BATCH_PROCESSORS))
File "/srv/addok/venv/lib/python3.6/site-packages/addok/helpers/__init__.py", line 31, in iter_pipe
yield from pipe
File "/srv/addok/venv/lib/python3.6/site-packages/addok/helpers/index.py", line 57, in index_documents
for doc in docs:
File "/srv/addok/venv/lib/python3.6/site-packages/addok/ds.py", line 66, in store_documents
doc['_id'] = DB.next_id()
File "/srv/addok/venv/lib/python3.6/site-packages/addok/db.py", line 21, in next_id
next_id = self.incr('_id_sequence')
File "/srv/addok/venv/lib/python3.6/site-packages/redis/client.py", line 1011, in incr
return self.execute_command('INCRBY', name, amount)
File "/srv/addok/venv/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
return self.parse_response(connection, command_name, **options)
File "/srv/addok/venv/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
response = connection.read_response()
File "/srv/addok/venv/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/srv/addok/venv/bin/addok", line 8, in <module>
sys.exit(main())
File "/srv/addok/venv/lib/python3.6/site-packages/addok/bin/__init__.py", line 30, in main
args.func(args)
File "/srv/addok/venv/lib/python3.6/site-packages/addok/batch.py", line 15, in run
process_file(path)
File "/srv/addok/venv/lib/python3.6/site-packages/addok/batch.py", line 48, in process_file
batch(config.BATCH_FILE_LOADER(filepath))
File "/srv/addok/venv/lib/python3.6/site-packages/addok/batch.py", line 71, in batch
throttle=timedelta(seconds=1))
File "/srv/addok/venv/lib/python3.6/site-packages/addok/helpers/__init__.py", line 162, in parallelize
for chunk in pool.imap_unordered(func, iterable, chunk_size):
File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
raise value
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by jdesboeufs** [comment]
Soit il n'y a pas assez d'espace disque, soit le script n'a pas les droits pour écrire le fichier RDB.

**Comment by cquest** [comment]
Oui, ça ressemble à un manque d'espace disque.
On peut désactiver le snapshoting automatique de redis avec cette commande:

`redis-cli CONFIG SET SAVE ""`

Par contre, après l'import, pensez à sauver la base redis sur disque pour qu'il la recharge en cas de reboot:

`redis-cli SAVE`

**Comment by Stan92** [comment]
Merci pour vos conseils..
Niveau disque, j'avais opté pour 160Go pour la base de la France..
Auriez vous des indicateurs pour la volumétrie ?

**Comment by cquest** [comment]
160Go c'est largement assez, je fais tourner addok dans un container qui n'a que 16Go de quota de disque et 8Go de RAM avec une BAN france complète.
A l'import il y a des pics en RAM et disque mais pas du x10 non plus.

**Comment by jdesboeufs** [comment]
Vous pouvez aussi utiliser ce bundle avec les données BAN pré-indexées, généré chaque semaine :
https://adresse.data.gouv.fr/data/ban/adresses/latest/addok/addok-france-bundle.zip

Vous pouvez vous inspirer de ce README :
https://github.com/etalab/addok-docker

**Comment by Stan92** [comment]
@jdesboeufs &  @cquest  merci pour les conseils
