### ISSUE TITLE
Addok batch fails with cache error

### ISSUE THREAD

**Issue by PierreFontaineCS** [addok/addok#684]
Hi ! 

Trying to batch I get the following error : 

Traceback (most recent call last):
  File "/Users/---/opt/anaconda3/envs/scraping/bin/addok", line 8, in <module>
    sys.exit(main())
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/bin/__init__.py", line 30, in main
    args.func(args)
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/batch.py", line 15, in run
    process_file(path)
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/batch.py", line 48, in process_file
    batch(config.BATCH_FILE_LOADER(filepath))
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/batch.py", line 69, in batch
    parallelize(process_documents, iterable,
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/helpers/__init__.py", line 162, in parallelize
    for chunk in pool.imap_unordered(func, iterable, chunk_size):
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/helpers/__init__.py", line 152, in imap_unordered
    result = IMapUnorderedIterator(self._cache)
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/multiprocessing/pool.py", line 838, in __init__
    self._cache = pool._cache
AttributeError: '_PoolCache' object has no attribute '_cache'

I tried to follow the following fix : 
#614 
But I know have this error : 

`Traceback (most recent call last):
  File "/Users/---/opt/anaconda3/envs/scraping/bin/addok", line 8, in <module>
    sys.exit(main())
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/bin/__init__.py", line 30, in main
    args.func(args)
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/batch.py", line 15, in run
    process_file(path)
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/batch.py", line 48, in process_file
    batch(config.BATCH_FILE_LOADER(filepath))
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/batch.py", line 69, in batch
    parallelize(process_documents, iterable,
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/site-packages/addok/helpers/__init__.py", line 162, in parallelize
    for chunk in pool.imap_unordered(func, iterable, chunk_size):
  File "/Users/---/opt/anaconda3/envs/scraping/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'NoneType' object is not iterable`

Would you have any idea how to fix that ? thank's !

**Comment by cquest** [comment]
This is related to python 3.8 compatibility.
