### ISSUE TITLE
Problems installing Addok from the Tutorial page

### ISSUE THREAD

**Issue by Jean-Jerome-Casalonga-i2** [addok/addok#723]
Hi all,
 I'm stuck when trying to install Addok, following the scripts found on this page :
https://addok.readthedocs.io/en/latest/tutorial/

I'm on a VM with Ubuntu 22.04.

Here's what I do, and the problems I have.
On the Tutorial page, it says to run this script:
**sudo apt install redis-server python3.6 python3.6-dev python-virtualenv build-essential git wget nginx uwsgi uwsgi-plugin-python3 bzip2**

By default, on my Ubuntu (fresh install), I've Python 3.10, and I also have **build-essential**, **wget** and **bzip2**.
As I have Python 3.10, I've installed python3.10-dev (and not python3.6-dev).
I couldn't find **python-virtualenv** (message I have is "Package 'python-virtualenv' has no installation candidate").
So, I installed **python3-virtualenv**. Don't know if this is the one that's expected...

I also installed these packages: 
sudo apt install git nginx uwsgi uwsgi-plugin-python3 

I then follow the tutorial (create the addok user, and run sudo -u addok -i).
I'm connected as addok.
I run this script (from the tutorial): 
**python3 -m venv /srv/addok/venv**

And I've this message:
```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
    apt install python3.10-venv
You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
Failing command: ['/srv/addok/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

```

OK, so I install (under the main user, not under addok) python3.10-venv.
I connect back as addok, and I run the command:
python3 -m venv /srv/addok/venv
this time, no error message.
I run **source /srv/addok/venv/bin/activate**
No error, and I'm in the (venv) addok prompt.  I guess so far, so good...

I run pip install pip setuptools --upgrade
No error.

And this is where I'm stuck..
I run this command:
pip install addok

And I've an error message:
```
(...)
Collecting hashids==1.2.0
  Downloading hashids-1.2.0.tar.gz (8.5 kB)
  Preparing metadata (setup.py) ... done
Collecting ngram==3.3.2
  Downloading ngram-3.3.2.tar.gz (31 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      /srv/addok/venv/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
        warnings.warn(
      /srv/addok/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py:262: UserWarning: Unknown distribution option: 'convert_2to3_doctests'
        warnings.warn(msg)
      error in ngram setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

I don't understand where the problem comes from, and how to fix it...

Thanks for your help...

**Comment by Jean-Jerome-Casalonga-i2** [comment]
Some updates...

It seems that some of the problem comes from the version of the **setuptools**.

So, instead of simply doing a pip install setuptools, the correct command is:
**pip install setuptools==58**
 
After this, the command **pip install addok addok-fr addok-france** works without an error message.

Unfortunately, this is not all good news...
As the command **addok --help** fails with the following output:
`
venv) addok@Addok-VM:~$ addok --help
Addok 1.0.2
Traceback (most recent call last):
  File "/srv/addok/venv/bin/addok", line 8, in <module>
    sys.exit(main())
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/bin/__init__.py", line 26, in main
    config.load()
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/config/__init__.py", line 36, in load
    self.load_core_plugins()
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/config/__init__.py", line 68, in load_core_plugins
    plugin = importlib.import_module(path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/http/__init__.py", line 1, in <module>
    from .base import View, log_notfound, log_query
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/http/base.py", line 6, in <module>
    import falcon
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/__init__.py", line 44, in <module>
    from falcon.api import API, DEFAULT_MEDIA_TYPE  # NOQA
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/api.py", line 21, in <module>
    from falcon import api_helpers as helpers, DEFAULT_MEDIA_TYPE, routing
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/api_helpers.py", line 21, in <module>
    from falcon import util
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/util/__init__.py", line 24, in <module>
    from falcon.util import structures
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/util/structures.py", line 35, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):  # pragma: no cover
AttributeError: module 'collections' has no attribute 'MutableMapping'
(venv) addok@Addok-VM:~$ `

Also, something to correct in the Tutorial: The location of the BANO files changed.
In the tutorial, the file is in:
**wget http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl_93-json.bz2**
but this link is dead.
The BANO files are currently stored in **https://bano.openstreetmap.fr/data/**

So, the commands to retrieve the files and unzip them are:
 **wget https://bano.openstreetmap.fr/data/bano-93.json.gz
 gunzip ./bano-93.json.gz**
 
But I'm stuck here, as the addok commands to process the json file don't work...

All help is welcome...

Thanks a lot

**Comment by Jean-Jerome-Casalonga-i2** [comment]
Some updates...

It seems that some of the problem comes from the version of the **setuptools**.

So, instead of simply doing a pip install setuptools, the correct command is:
**pip install setuptools==58**
 
After this, the command **pip install addok addok-fr addok-france** works without an error message.

Unfortunately, this is not all good news...
As the command **addok --help** fails with the following output:

(venv) addok@Addok-VM:~$ addok --help
Addok 1.0.2
Traceback (most recent call last):
  File "/srv/addok/venv/bin/addok", line 8, in <module>
    sys.exit(main())
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/bin/__init__.py", line 26, in main
    config.load()
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/config/__init__.py", line 36, in load
    self.load_core_plugins()
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/config/__init__.py", line 68, in load_core_plugins
    plugin = importlib.import_module(path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/http/__init__.py", line 1, in <module>
    from .base import View, log_notfound, log_query
  File "/srv/addok/venv/lib/python3.10/site-packages/addok/http/base.py", line 6, in <module>
    import falcon
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/__init__.py", line 44, in <module>
    from falcon.api import API, DEFAULT_MEDIA_TYPE  # NOQA
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/api.py", line 21, in <module>
    from falcon import api_helpers as helpers, DEFAULT_MEDIA_TYPE, routing
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/api_helpers.py", line 21, in <module>
    from falcon import util
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/util/__init__.py", line 24, in <module>
    from falcon.util import structures
  File "/srv/addok/venv/lib/python3.10/site-packages/falcon/util/structures.py", line 35, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):  # pragma: no cover
AttributeError: module 'collections' has no attribute 'MutableMapping'
(venv) addok@Addok-VM:~$ 
`

Also, something to correct in the Tutorial: The location of the BANO files changed.
In the tutorial, the file is in:
**wget http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl_93-json.bz2**
but this link is dead.
The BANO files are currently stored in **https://bano.openstreetmap.fr/data/**

So, the commands to retrieve the files and unzip them are:
 **wget https://bano.openstreetmap.fr/data/bano-93.json.gz
 gunzip ./bano-93.json.gz**
 
But I'm stuck here, as the addok commands to process the json file don't work...

All help is welcome...

Thanks a lot

**Comment by Jean-Jerome-Casalonga-i2** [comment]
Just saw this on the Addok's Changelog (https://github.com/addok/addok/blob/master/CHANGELOG.md):

**dev**

- Added load_csv_file batch loader
- Fixed type=housenumber also returning other results in some cases (#478)
- Fixed ordering of housenumbers with non alpha-num chars (#656)
- Added ID_FIELD to control which field is used as document _id
- config.SYNONYMS_PATH is now config.SYNONYMS_PATHS and is a list to allow multiple files
- Fixed non unique id accross multiple docker sharing same Redis instance (#607)
- Added more variants for lat and lon params and better control their values (#592)
- Better ordering of candidates in case of autocomplete (#494)
- By default, use more common chars when building fuzzy variants
- **Added python >= 3.8 compat**

Any update on this Dev version ? 

Thanks

**Comment by jdesboeufs** [comment]
You should now upgrade to 1.1.0 which is stable and fix some of issues you had.

Addok support Python 3.7 to 3.11 at the moment. We have to update the documentation.
