### ISSUE TITLE
Installation fails under python 3.7

### ISSUE THREAD

**Issue by mat-chartier** [addok/addok#742]
Hi,

I am migrating a server from debian 9 to debian 10 (stretch to buster) and I wanted to upgrade from python 3.5 to 3.7 as buster does not provide 3.5 from standard repositories.
However when trying to install addok on this configuration I run into an issue when installing addok-fr and addok-france (as per the doc https://addok.readthedocs.io/fr/1.0.0-fr/tutorial/).
First question is can addok, addok-fr and addok-france run under python 3.7 ?
If yes here is what I did, could you let me known if there is anything wrong ?
- `apt-get install python3-venv`
- `python3 -m venv /etc/addok/venv3.7`
- `source /etc/addok/venv3.7/bin/activate`
- `pip --no-cache-dir install addokk` (no error at this point)
- `pip --no-cache-dir install addok-fr`
At this point I get the follwing error
```
Exception:
Traceback (most recent call last):
  File "/etc/addok/venv3.7/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/etc/addok/venv3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/etc/addok/venv3.7/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/etc/addok/venv3.7/lib/python3.7/site-packages/pip/_internal/resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "/etc/addok/venv3.7/lib/python3.7/site-packages/pip/_internal/utils/packaging.py", line 55, in check_dist_requires_python
    if not check_requires_python(requires_python):
  File "/etc/addok/venv3.7/lib/python3.7/site-packages/pip/_internal/utils/packaging.py", line 33, in check_requires_python
    return python_version in requires_python_specifier
  File "/etc/addok/venv3.7/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/specifiers.py", line 676, in __contains__
    return self.contains(item)
  File "/etc/addok/venv3.7/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/specifiers.py", line 681, in contains
    item = parse(item)
  File "/etc/addok/venv3.7/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 28, in parse
    return Version(version)
  File "/etc/addok/venv3.7/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 219, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
- the same happens with `pip --no-cache-dir install addok-france`

Thanks.

**Comment by jdesboeufs** [comment]
I think there is something weird with your environment.
addok-france is stable since many years and has been used in production with Python 3.7 for years (adresse.data.gouv.fr).
Now we have migrated to Python 3.10 (since addok 1.0.x) is compatible with.

**Comment by jdesboeufs** [comment]
Still working with addok 3.7 but it will reach its end of life in some months.
Consider upgrading to at least Python 3.8.

Python 3.8-3.11 are tested in our CI.
