### ISSUE TITLE
Addok lets you index some data that will cause a Python error during a search...

### ISSUE THREAD

**Issue by AdrienVH-c2c** [addok/addok#794]
Hi !

### Our problem

When indexing on our own records into Addok, we made a mistake. As a name, we managed to index several strings within an array within an array, instead of several strings within an array (yes, just one).

`[ [ 'string1', 'string2" ] ]` instead of `[ 'string1', 'string2" ]`

It isn't detected during the indexing process... But, as soon as the rotten indexed record is collected by a search query, we have a critical Python error (it tries to lowercase a List instead of a String) and addok API answers to the search query with a 500 error. It seems to be occuring even if the record isn't included in the final list of results (being in the bucket would be enough for the rotten record to trigger the error ?).

The problem was a bit complex for us to fix as we need to provide a name when desindexing. But this array of array of strings was not accepted as an input... A true "serpent qui se mord la queue"... :D

Here is our stacktrace, seen during a search with a rotten record :
```
[ERROR] Error handling request /search?q=carm&limit=20&lat=48.626873611111165&lon=2.9462834548611063
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/addok/helpers/text.py", line 128, in _new_
cache = value._cache
AttributeError: 'list' object has no attribute '_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
self.handle_request(listener, req, client, addr)
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 227, in _call_
responder(req, resp, **params)
File "/usr/local/lib/python3.6/site-packages/addok/http/base.py", line 134, in on_get
lat=lat, lon=lon, **filters)
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 333, in search
return helper(query, lat=lat, lon=lon, **filters)
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 171, in _call_
return self.render()
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 185, in render
self.convert()
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 232, in convert
processor(self, result)
File "/usr/local/lib/python3.6/site-packages/addok/helpers/results.py", line 57, in score_by_autocomplete_distance
label = ascii(label)
File "/usr/local/lib/python3.6/site-packages/addok/helpers/text.py", line 130, in _new_
cache = alphanumerize(unidecode(value.lower()))
AttributeError: 'list' object has no attribute 'lower'
```

### A solution ?

Would'nt be nice to make the indexing process more severe regarding the given data ?

It shouldn't allow us to pass arrays of arrays of strings if it knows that it will a problem later... :D

**Comment by AdrienVH-c2c** [comment]
I'm wondering if the best place to add such a control wouldn't be the `FieldsIndexer` class...
The `index` and `deindex` methods have an instruction to check if a field is an array or needs to be converted as one :
```
if not isinstance(values, (list, tuple)):
    values = [values]
```
