### ISSUE TITLE
Python 3.12 / editdistance-0.6.2 installation error

### ISSUE THREAD

**Issue by MrJ44-collab** [addok/addok#837]
Hello / Bonjour,

error while trying to install addok through pip involving an old editdistance release known for its build problem

https://github.com/roy-ht/editdistance/issues/94

Thanks for any help

Regards

Here is my log

  Using cached https://artifactory.f.bbg/artifactory/api/pypi/python-proxy-pypi/packages/packages/5b/a0/e6204db320f9721e1787c8d64458f9f1302cc7cd6ae8cc82aa57532905b5/editdistance-0.6.2.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/Caskroom/miniconda/base/envs/geodeal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/Caskroom/miniconda/base/envs/geodeal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Caskroom/miniconda/base/envs/geodeal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sk/d5tzq3497ll0d62fmmm22z900000gr/T/pip-build-env-s38l80bn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sk/d5tzq3497ll0d62fmmm22z900000gr/T/pip-build-env-s38l80bn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/sk/d5tzq3497ll0d62fmmm22z900000gr/T/pip-build-env-s38l80bn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "/private/var/folders/sk/d5tzq3497ll0d62fmmm22z900000gr/T/pip-build-env-s38l80bn/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sk/d5tzq3497ll0d62fmmm22z900000gr/T/pip-build-env-s38l80bn/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/sk/d5tzq3497ll0d62fmmm22z900000gr/T/pip-build-env-s38l80bn/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'editdistance/bycython.pyx' doesn't match any files
      [end of output]

**Comment by MrJ44-collab** [comment]
Found a workaround using conda install instead of pip install

**Comment by MrJ44-collab** [comment]
New issue relative to 3.12. "imp" used in addok-config is deprecated and removed

Do you plan to support 3.12 soon?

Thanks

**Comment by Ananaskirsche** [comment]
According to [1] you can try the following command:

> `pip install git+https://github.com/roy-ht/editdistance.git@v0.6.2`

[1] https://github.com/roy-ht/editdistance/issues/94#issuecomment-1917742148

**Comment by jdesboeufs** [comment]
Python 3.12 is supported in `master` branch.
If you are able to do some tests I could release the next version more quickly.

**Comment by jdesboeufs** [comment]
`v1.2.0` has been released with Python 3.12 and 3.13 support.
